# Generated by Django 4.1 on 2023-02-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inv'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=100)),
                ('deleted', models.CharField(max_length=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('uid', models.IntegerField(default=0)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('account_number', models.CharField(max_length=25)),
                ('branch_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='inv',
            name='inv_state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inv',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
