# Generated by Django 4.1 on 2023-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bank_details_alter_inv_inv_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
