# Generated by Django 4.1 on 2023-02-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnd',
            name='cnd_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
