# Generated by Django 4.1 on 2023-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_details_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
