# Generated by Django 4.1 on 2023-02-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_details_aadhaar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='docstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('verification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('store_data_image', models.TextField(blank=True, null=True)),
                ('deleted', models.CharField(max_length=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
