# Generated by Django 4.1 on 2023-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cnd_max_proposal_cnd_min_proposal_cnd_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnd',
            name='rate',
        ),
        migrations.AlterField(
            model_name='cnd',
            name='max_proposal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
