# Generated by Django 4.1 on 2023-02-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_cnd_rate_alter_cnd_max_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnd',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cnd',
            name='min_proposal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
