# Generated by Django 4.1 on 2023-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cnd_rate_alter_cnd_min_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnd',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
