# Generated by Django 4.1 on 2023-03-04 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_b2b_product_investment_utr_detail_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 23, 35, 21, 203014)),
        ),
    ]
