# Generated by Django 4.1 on 2023-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_b2b_product_investment_utr_detail_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='txn_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
