# Generated by Django 4.1 on 2023-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_b2b_product_investment_utr_detail_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='deleted',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='reconcile',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
