# Generated by Django 4.1 on 2023-03-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_b2b_product_investment_utr_detail_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='deleted',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
    ]
