# Generated by Django 4.1 on 2023-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_b2b_product_investment_utr_detail_reconcile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='escrow_status',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
    ]
