# Generated by Django 4.1 on 2023-03-07 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_b2b_product_investment_utr_detail_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='deleted',
            field=models.CharField(default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='proposal_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='pt_ref_id',
            field=models.CharField(default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='b2b_product_investment_utr_detail',
            name='reconcile',
            field=models.CharField(default='N', max_length=3, null=True),
        ),
    ]
